### PR TITLE
Adding Gluon

### PR DESCRIPTION
**Pull request by yytdfc**
I'm adding Gluon notebook on Cifar dataset.
Issue #4
Training log on GTX1080:
```
Epoch   0: loss: 1.8391
Epoch   1: loss: 1.3565
Epoch   2: loss: 1.1344
Epoch   3: loss: 0.9630
Epoch   4: loss: 0.8310
Epoch   5: loss: 0.7168
Epoch   6: loss: 0.6256
Epoch   7: loss: 0.5460
Epoch   8: loss: 0.4709
Epoch   9: loss: 0.4007
CPU times: user 1min 21s, sys: 11.4 s, total: 1min 33s
Wall time: 1min 3s

Accuracy:  0.768930288462
```

### CODE REVIEW

**Comment by ilkarman** [comment]
Thanks very interesting example! Does gluon not let you apply standard Relu as a layer (after max-pooling)?

**Comment by yytdfc** [comment]
ReLU is not in gluon.nn package, but `gluon.nn.Activation('relu')` or `gluon.nn.LeakyReLU(0)`, they will do the same work. Maybe the former is better?

**Comment by ilkarman** [comment]
@yytdfc I ran both and they take the same amount of time. I agree, I'll replace it with the former in my run just for consistency but nice to know that LeakyReLU gives the extra flexibility!

**Comment by yytdfc** [comment]
In this case, PyTorch performs better than Gluon on GTX1080, but Gluon performs better on much deeper network. Would you like to give approximate memory usage and utility of K80?

**Pull request merged**
