### PR TITLE
Knet notebooks added

### PR DESCRIPTION
**Pull request by denizyuret**
Dear Ilia, I am the author of [Knet](https://github.com/denizyuret/Knet.jl), the popular Julia deep learning package. You can find some info on Julia and Knet at:
* [Julia website](https://julialang.org/)
* [Knet documentation](https://denizyuret.github.io/Knet.jl/latest)
* [Video tutorial at JuliaCon-2017](http://www.denizyuret.com/2017/05/juliacon-2017-berkeley-june-20-24.html)
* [Paper at NIPS MLSys Workshop](http://www.denizyuret.com/2016/12/knet-beginning-deep-learning-with-100.html)

As many people in the Julia community are interested in performance and readability comparisons with Python and comparisons between ML systems in general, I thought I would contribute Julia/Knet implementations of your examples. I tried to mirror the examples as close as I could, running them on a K80 server with "Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz" CPUs. If you want to run them on your setup, all you need to do is to install the latest version of Julia and add the packages given at the top of each notebook before you run. I recommend running them twice to isolate compilation costs. Thanks for your other examples which I will share with the Julia community.

### CODE REVIEW

**Comment by ilkarman** [comment]
Thank you so much for the contribution Deniz, that's fantastic! Really excited to try Julia with this. Out of interest - was this run on the Azure VMs or locally (since you have K80)?

**Comment by denizyuret** [comment]
I ran it locally on the univ cluster. Therefore I am not sure about the
timing comparison.  Since most of the work is done by cudnn I assume the
results will be close on Azure, but we should probably try everything on
the same machine to make sure.

**Comment by denizyuret** [comment]
Can I help test the Julia notebooks on your setup?  I don't have much
experience with Azure, I typically work with AWS, but if you have an
existing machine image I can at least help setup the Julia stuff on it.

**Comment by ilkarman** [comment]
Deniz, when I run the line: 

`Pkg.checkout("Knet","ilkarman") # make sure we have the right Knet version`

I get the error:

> INFO: Checking out Knet ilkarman...
INFO: Pulling Knet latest ilkarman...
WARNING: Knet is fixed at 0.8.3+ conflicting with top-level requirement: [0.8.3,0.8.3+)
fixed packages introduce conflicting requirements for AutoGrad: 
         Knet requires versions [0.0.9,∞) [none of the available versions can satisfy this requirement]
       available versions are 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6 and 0.0.7

Stacktrace:
 [1] check_requirements(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/query.jl:222
 [2] resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:496
 [3] resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/entry.jl:479
 [4] (::Base.Pkg.Entry.##16#18{String,String,Bool,Bool})(::Base.LibGit2.GitRepo) at ./pkg/entry.jl:236
 [5] transact(::Base.Pkg.Entry.##16#18{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:882
 [6] with(::Base.Pkg.Entry.##15#17{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:608
 [7] checkout(::String, ::String, ::Bool, ::Bool) at ./pkg/entry.jl:226
 [8] (::Base.Pkg.Dir.##3#6{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool}})() at ./pkg/dir.jl:33
 [9] cd(::Base.Pkg.Dir.##3#6{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool}}, ::String) at ./file.jl:70
 [10] withenv(::Base.Pkg.Dir.##2#5{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool},String}, ::Pair{String,String}, ::Vararg{Pair{String,String},N} where N) at ./env.jl:157
 [11] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N} where N) at ./pkg/dir.jl:32
 [12] #checkout#1(::Bool, ::Bool, ::Function, ::String, ::String) at ./pkg/pkg.jl:188
 [13] checkout(::String, ::String) at ./pkg/pkg.jl:188

Is this something to do with my install?

**Comment by denizyuret** [comment]
It seems like your packages are out of date.  Pkg.update() should fix it.

I told my student Omer (cc'ed) to try running the Knet benchmarks on your
Azure setup as well.  But he says the machine came without the proper cuda
drivers installed.  Maybe he picked the wrong machine option or something.
If you help us launch the right Azure machine with the right image, we can
try to replicate the experiment as well.

best,
deniz

**Comment by ilkarman** [comment]
Ah thank you - that seems to have pulled some new repos but seemed to end with an error:

> INFO: Cloning cache of Reactive from https://github.com/JuliaGizmos/Reactive.jl.git
> INFO: Cloning cache of LaTeXStrings from https://github.com/stevengj/LaTeXStrings.jl.git
> INFO: Cloning cache of AxisArrays from https://github.com/JuliaArrays/AxisArrays.jl.git
> INFO: Cloning cache of DualNumbers from https://github.com/JuliaDiff/DualNumbers.jl.git
> INFO: Cloning cache of IndexedTables from https://github.com/JuliaComputing/IndexedTables.jl.git
> INFO: Cloning cache of CSV from https://github.com/JuliaData/CSV.jl.git
> INFO: Cloning cache of Hiccup from https://github.com/JunoLab/Hiccup.jl.git
> INFO: Updating Knet ilkarman... 48d49243 → 5c7d4822
> INFO: Computing changes...
> ERROR: fixed packages introduce conflicting requirements for BinDeps:
>        available versions are 0.0.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.3.20, 0.3.21, 0.3.22, 0.3.23, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.7, 0.5.0 and 0.6.0
> 

Regarding the correct machine. Maybe @gopitk can chime in regarding the cuda version (I think by default we have version 8.0 with cudnn 5).

For the benchmarks I have been using the [Deep Learning Virtual Machine (DLVM)](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-ads.dsvm-deep-learning), the NC12 series

**Comment by denizyuret** [comment]
It seems you have a pre-existing Julia setup that is interfering with the
installation. Some of these packages seem to be fixed to stay in one
out-of-date version which seems to be causing the problem.  I would
recommend deleting ~/.julia (or mv ~/.julia to ~/.julia.bak), and do a
fresh start with the appropriate Pkg.add commands.  Also make sure you are
using the latest released Julia version (0.6.1).  Finally Pkg.build("Knet")
will need nvcc and the cuda/cudnn libraries to be in your path.

**Comment by denizyuret** [comment]
We just updated the PR to use Azure timings.  Only the CNN changed to 148 seconds.  Let us know if you need help with the Azure setup.

**Comment by kirnap** [comment]
@ilkarman I create a machine image Deep_Learning_Virtual_Machine(Knet_included) including fresh locally installed julia along with required packages upon your Deep Learning Virtual Machine (DLVM). Let me know if you have any problems to run those tests on that image.

**Comment by ilkarman** [comment]
@kirnap Thank you for helping out. I will check out the image you created. I'm glad the timings haven't changed. I figured it was about time I re-ran all the timings to be able to standardise them so will do that in the couple of days.

**Comment by gopitk** [comment]
We are in the process of updating the Ubuntu DSVM to Julia 0.6.0.1, cuDNN 6.  (CUDA will stay at 8) in the next few days. Previously it was at Julia 0.5, cuDNN5.

**Comment by kirnap** [comment]
@gopitk It would be better to update latest version of Julia which is 0.6.1, and cuDNN also has 7th version.

**Pull request merged**
